#!/bin/bash
AC=$(upower --show-info /org/freedesktop/UPower/devices/line_power_AC | grep online | awk '{print $2}')
PER=$(upower --show-info /org/freedesktop/UPower/devices/DisplayDevice | grep percentage | awk '{print $2}')

if [[ $AC == "yes" ]]; then
        echo "+ "$PER
else
        echo "- "$PER
fi

